import { EvaluationMetrics, LearningModelKind, LearningModelStatus } from "../../lib/api";
import { useI18n } from "../../lib/i18n";

const copy = {
  en: { title: "Learning models", subtitle: "Learning from the current reviewed transactions, including manual entries and corrections.", back: "Back to settings", loading: "Loading model...", reviewed: "Reviewed transactions", pending: "Pending updates", version: "Model version", evaluation: "Later import evaluation", unseen: "Unseen counterparties", hint: "Whole imports stay together. Settings are chosen on validation data; these results use a later test partition. Accuracy is measured on held-out rows, not the saved training examples.", unseenHint: "A separate test holds out merchant names entirely. This measures generalization; suggestion thresholds are not evaluated in this test.", insufficient: "More independent reviewed imports are needed before reliable evaluation is possible.", head: "Prediction", samples: "Test rows", accuracy: "Accuracy", baseline: "Majority baseline", f1: "Macro F1", top: "Top three", coverage: "Suggestion coverage", precision: "Suggestion precision", type: "Type", category: "Category", description: "Description", limits: "Low evidence leaves suggestions unselected. Model scores are estimates, not guarantees; every import still requires review.", refresh: "Refresh", calibration: "Calibration checks", score: "Mean score", observed: "Observed accuracy", count: "Rows" },
  sv: { title: "Inlärningsmodeller", subtitle: "Lär från aktuella granskade transaktioner, inklusive manuella poster och rättelser.", back: "Tillbaka till inställningar", loading: "Läser modellen…", reviewed: "Granskade transaktioner", pending: "Väntande uppdateringar", version: "Modellversion", evaluation: "Utvärdering på senare importer", unseen: "Nya motparter", hint: "Hela importer hålls ihop. Inställningar väljs på valideringsdata; resultaten här använder senare testdata. Träffsäkerheten mäts på undanhållna rader, inte träningsexemplen.", unseenHint: "Ett separat test undanhåller handlarens namn helt. Det mäter generalisering; förslagströsklar utvärderas inte i detta test.", insufficient: "Fler oberoende granskade importer behövs innan tillförlitlig utvärdering är möjlig.", head: "Förutsägelse", samples: "Testrader", accuracy: "Träffsäkerhet", baseline: "Majoritetsbaslinje", f1: "Makro F1", top: "Topp tre", coverage: "Förslagstäckning", precision: "Förslagsprecision", type: "Typ", category: "Kategori", description: "Beskrivning", limits: "Svagt underlag lämnar förslag tomma. Modellpoäng är uppskattningar, inte garantier; varje import kräver fortfarande granskning.", refresh: "Uppdatera", calibration: "Kalibreringskontroll", score: "Medelpoäng", observed: "Observerad träffsäkerhet", count: "Rader" },
};
const kinds: LearningModelKind[] = ["type", "category", "description"];
const percentage = (value: number | null | undefined) => value == null ? "—" : `${(value * 100).toFixed(1)}%`;

// These reports describe held-out predictions, not accuracy on the final refit.
export function ModelEvaluation({ status }: { status: LearningModelStatus }) {
  const { locale } = useI18n();
  const c = copy[locale];
  const report = status.report;
  if (!report) return null;
  const table = (metrics: Record<LearningModelKind, EvaluationMetrics>, suggestions: boolean) => <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{[c.head, c.samples, c.accuracy, c.baseline, c.f1, c.top, ...(suggestions ? [c.coverage, c.precision] : [])].map(name => <th key={name} className="whitespace-nowrap p-3 text-left">{name}</th>)}</tr></thead><tbody>{kinds.map(kind => <tr key={kind} className="border-t border-[#e5ece7]"><th className="p-3 text-left">{c[kind]}</th><td className="p-3">{metrics[kind].samples}</td>{[metrics[kind].accuracy, metrics[kind].baseline_accuracy, metrics[kind].macro_f1, metrics[kind].top_three_accuracy, ...(suggestions ? [metrics[kind].coverage, metrics[kind].suggestion_precision] : [])].map((value, index) => <td key={index} className="whitespace-nowrap p-3">{percentage(value)}</td>)}</tr>)}</tbody></table></div>;
  return <div className="space-y-5">
      {report.description_comparison && <section className="card p-5"><h2>{locale === "en" ? "Does category context help descriptions?" : "Hjälper kategorikontext beskrivningar?"}</h2><p className="lab-help">{locale === "en" ? "Both versions use the same later test rows. The blend was selected on earlier validation with predicted categories. Lower log loss is better. The separate unseen-name report below evaluates the direct expert only." : "Båda versionerna använder samma senare testrader. Blandningen valdes på tidigare validering med förutsagda kategorier. Lägre log loss är bättre. Testet för nya namn nedan utvärderar bara direktexperten."}</p><div className="overflow-x-auto"><table className="lab-parameter-table"><thead><tr><th>{c.description}</th><th>{c.accuracy}</th><th>Log loss</th><th>{c.coverage}</th><th>{c.precision}</th></tr></thead><tbody>{(["independent", "blended"] as const).map(key => { const metrics = report.description_comparison![key]; return <tr key={key}><th scope="row">{locale === "en" ? key === "independent" ? "Direct only" : "Selected blend" : key === "independent" ? "Endast direkt" : "Vald blandning"}</th><td>{percentage(metrics.accuracy)}</td><td>{metrics.log_loss?.toFixed(3) ?? "—"}</td><td>{percentage(metrics.coverage)}</td><td>{percentage(metrics.suggestion_precision)}</td></tr>; })}</tbody></table></div></section>}
      <section className="card min-w-0 space-y-4 p-5 sm:p-6"><h2>{c.evaluation}</h2><p className="text-sm text-muted">{c.hint}</p>{report.test_samples ? table(report.chronological, true) : <p>{c.insufficient}</p>}<p className="text-sm text-muted">{c.limits}</p>
        {report.test_samples > 0 && <details><summary className="cursor-pointer text-sm font-semibold">{c.calibration}</summary><div className="mt-3 grid gap-4 md:grid-cols-3">{kinds.map(kind => <div key={kind}><h3>{c[kind]}</h3><table className="mt-2 w-full text-xs"><thead><tr><th>{c.score}</th><th>{c.observed}</th><th>{c.count}</th></tr></thead><tbody>{report.chronological[kind].calibration_bins?.map((bin, index) => <tr key={index}><td className="p-2">{percentage(bin.score)}</td><td className="p-2">{percentage(bin.accuracy)}</td><td className="p-2">{bin.count}</td></tr>)}</tbody></table></div>)}</div></details>}
      </section>
      {report.unseen_counterparty && <section className="card min-w-0 space-y-4 p-5 sm:p-6"><h2>{c.unseen}</h2><p className="text-sm text-muted">{c.unseenHint}</p>{table(report.unseen_counterparty, false)}</section>}
  </div>;
}
